version: '3.8'

services:
  telegram-torrent-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-torrent-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - torrent-network
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  torrent-network:
    driver: bridge

volumes:
  downloads:
    driver: local
  logs:
    driver: local
